{% set name = "apache-airflow-providers-amazon" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-amazon-{{ version }}.tar.gz
  sha256: c6d5d779698fc984e5695e758b2549cfcaba906e6b86bc89b5b45ef5da987670

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - wheel
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - boto3 >=1.15.0,<1.19.0
    - jsonpath-ng >=1.5.3
    - pandas >=0.17.1,<2.0
    - redshift_connector >=2.0.888,<2.1
    - sqlalchemy-redshift >=0.8.6,<0.9
    - watchtower >=2.0.1,<2.1

test:
  imports:
    - airflow.providers.amazon
    - airflow.providers.amazon.aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Amazon integration (including Amazon Web Services, AWS) for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
