{% set name = "apache-airflow-providers-amazon" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-amazon-{{ version }}.tar.gz
  sha256: 20b81b83751e2e1e0b4037cae021f45a548d62ca8606133e83c4c79c61d563d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - boto3 >=1.15.0,<1.19.0
    - jsonpath-ng >=1.5.3
    - watchtower >=1.0.6,<1.1.0

test:
  imports:
    - airflow.providers.amazon
    - airflow.providers.amazon.aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Amazon integration (including Amazon Web Services, AWS) for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
